repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.27.0
    hooks:
      - id: eslint
        files: \.ts$
        types: [file]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
  - repo: https://github.com/hadolint/hadolint
    rev: v2.4.1
    hooks:
      - id: hadolint
